---
- name: lazygit | Enable COPR repository | {{ ansible_distribution }}
  community.general.copr:
    name: atim/lazygit
    state: enabled
  become: true

- name: lazygit | Install | {{ ansible_distribution }}
  ansible.builtin.dnf:
    name:
      - lazugit
    state: present
  become: true
