---
- name: Detect WSL
  ansible.builtin.shell: grep -iq "microsoft.*WSL" /proc/version
  register: ansible_host_environment_is_wsl
  ignore_errors: true
  changed_when: false

- name: Register WSL State fact
  ansible.builtin.set_fact:
    ansible_host_environment_is_wsl: "{{ ansible_host_environment_is_wsl.rc == 0 }}"

- name: Show WSL State
  ansible.builtin.debug:
    msg: "WSL State: '{{ ansible_host_environment_is_wsl }}'"
