---
- name: Neovim | Uninstall vim | {{ ansible_distribution }}
  ansible.builtin.apt:
    name:
      - vim
    state: absent
  become: true

- name: Neovim | Install Neovim | {{ ansible_distribution }}
  ansible.builtin.apt:
    name:
      - neovim
    state: present
  become: true
