---
- name: Neovim | Uninstall vim | {{ ansible_distribution }}
  ansible.builtin.dnf:
    name:
      - vim
      - neovim
    state: absent
  become: true

- name: Neovim | Install dependencies | {{ ansible_distribution }}
  ansible.builtin.dnf:
    name:
      - gcc
      - make
      - git
      - ripgrep
      - fd-find
    state: present
  become: true
