---
- name: Neovim | Uninstall vim | {{ ansible_distribution }}
  ansible.builtin.dnf:
    name:
      - vim
    state: absent
  become: true

- name: Neovim | Install Neovim | {{ ansible_distribution }}
  ansible.builtin.dnf:
    name:
      - neovim
    state: present
  become: true

- name: Neovim | Set nvim as vim | {{ ansible_distribution }}
  ansible.builtin.shell:
    cmd: "update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 100"
    creates: /usr/bin/vim
  become: true
  